import React, { useState, useEffect } from 'react';
import { useSOC } from '../context/SOCContext';
import {
  FileCheck2,
  Download,
  Printer,
  Copy,
  Check,
  ShieldAlert,
  Clock,
  Layers,
  ChevronRight,
  User,
  ExternalLink,
  Database,
  FileText,
  FileCode,
  Loader2,
  AlertCircle,
  Sparkles,
} from 'lucide-react';
import { RiskBadge } from '../components/common/RiskBadge';
import { StatusBadge } from '../components/common/StatusBadge';
import { EmptyState } from '../components/common/EmptyState';

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:5000';

export const ReportsPage = () => {
  const {
    reports,
    selectedReportId,
    navigateToReport,
    incidents,
    generateReportForIncident,
    addToast,
    loadDemoDataset,
    crewAIStatus,
    generateCrewAIReport,
  } = useSOC();

  const [copied, setCopied] = useState(false);
  const [saving, setSaving] = useState(false);
  const [exporting, setExporting] = useState(null);
  const [dbStatus, setDbStatus] = useState({ connected: false, loading: true });

  const activeReport =
    reports.find((r) => r.id === selectedReportId) || reports[0];

  useEffect(() => {
    const checkDb = async () => {
      try {
        const res = await fetch(`${API_BASE}/api/db-status`);
        const data = await res.json();
        setDbStatus({ connected: data.connected, loading: false });
      } catch {
        setDbStatus({ connected: false, loading: false });
      }
    };
    checkDb();
  }, []);

  const buildMarkdown = (r) => {
    if (!r) return '';
    return `# ${r.title || r.threat_title || 'Incident Investigation Report'}

**Report ID:** ${r.id || 'N/A'}
**Incident ID:** ${r.incident_id || 'N/A'}
**Generated Date:** ${r.generated_at || new Date().toISOString()}
**Generated By:** ${r.generated_by || 'ThreatWeave AI'}
**Risk Level:** ${r.risk_level || 'N/A'} (Score: ${r.risk_score || 'N/A'}/100)
**Confidence:** ${r.confidence || 'N/A'}%

---

## 1. Executive Summary
${r.executive_summary || r.threat_summary || 'N/A'}

---

## 2. Incident Context & Affected Assets

| Attribute | Value |
|-----------|-------|
| Target Entity | ${r.affected_user || 'N/A'} |
| Impacted System | ${r.affected_system || 'N/A'} |
| Affected Asset | ${r.affected_user_system || 'N/A'} |
| Attack Origin / Vector | ${r.source || r.attack_vector || 'N/A'} |
| Classification | ${r.threat_classification || r.type || 'N/A'} |
| Detection Time | ${r.detection_time || 'N/A'} |

---

## 3. Attack Progression & Forensic Timeline

${(r.timeline && r.timeline.length > 0)
  ? r.timeline.map((t, i) => `### ${i + 1}. [${t.timestamp || 'N/A'}] ${t.event || 'Event'}\n**Details:** ${t.details || 'N/A'}\n`).join('\n')
  : (r.correlated_timeline && r.correlated_timeline.length > 0)
    ? r.correlated_timeline.map((t, i) => `### ${i + 1}. [${t.timestamp || 'N/A'}] ${t.event_type || t.event || 'Event'}\n- **User:** ${t.user || 'N/A'}\n- **Source:** ${t.source || t.source_ip || 'N/A'}\n- **Action:** ${t.action || 'N/A'}\n- **Severity:** ${t.severity || 'N/A'}\n- **Details:** ${t.details || t.raw_log || 'N/A'}\n`).join('\n')
    : 'Timeline data unavailable.'}

---

## 4. Root Cause Analysis
${r.root_cause || (r.threat_explanation && (r.threat_explanation.technical || r.threat_explanation.non_technical)) || 'Root cause analysis pending.'}

---

## 5. Evidence Chain

${(r.evidence_list && r.evidence_list.length > 0)
  ? r.evidence_list.map((e, i) => `### Evidence Item ${i + 1}: ${e.id || e.title || 'N/A'}\n- **Type:** ${e.type || 'N/A'}\n- **Title:** ${e.title || 'N/A'}\n- **Timestamp:** ${e.timestamp || 'N/A'}\n- **Description:** ${e.description || 'N/A'}\n- **Extracted Value:** ${e.extracted_value || 'N/A'}\n- **Severity:** ${e.severity || 'N/A'}\n\n\`\`\`\n${e.raw_snippet || 'N/A'}\n\`\`\`\n`).join('\n')
  : 'No evidence items linked.'}

---

## 6. Immediate Containment Actions Taken

${(r.containment_actions && r.containment_actions.length > 0)
  ? r.containment_actions.map((c, i) => `${i + 1}. ${c}`).join('\n')
  : (r.recommended_response && r.recommended_response.filter((rr) => rr.category === 'Containment Actions' || rr.category === 'Immediate Actions').map((a, i) => `${i + 1}. **${a.priority || ''}:** ${a.action} (Target: ${a.target} - ${a.reason || ''})`).join('\n'))
    || 'No containment actions recorded.'}

---

## 7. Long-term Remediation & Strategic Hardening Recommendations

${(r.long_term_recommendations && r.long_term_recommendations.length > 0)
  ? r.long_term_recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n')
  : (r.recommended_response && r.recommended_response.filter((rr) => rr.category === 'Recovery Actions' || rr.category === 'Investigation Actions').map((a, i) => `${i + 1}. **${a.priority || ''}:** ${a.action} (Target: ${a.target} - ${a.reason || ''})`).join('\n'))
    || 'Recommendations pending.'}

---

## 8. MITRE ATT&CK Framework Mapping

${(r.ai_investigation_explanation && r.ai_investigation_explanation.risk_rationale) ? `**Risk Rationale:** ${r.ai_investigation_explanation.risk_rationale}\n\n` : ''}

**Attack Vector Summary:** ${r.attack_vector || (r.ai_investigation_explanation && r.ai_investigation_explanation.attack_vector_summary) || 'N/A'}

---

*Document generated by ThreatWeave Security Operations Platform — SIH 2026 Problem PS-01 Verified Dossier*
*${r.analyst_signoff || 'AI-Automated Forensic Analysis'}*
`;
  };

  const handleCopyMarkdown = () => {
    if (!activeReport) return;
    const markdown = buildMarkdown(activeReport);
    navigator.clipboard.writeText(markdown);
    setCopied(true);
    addToast('success', 'Report Copied', 'Markdown formatted report copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = async () => {
    if (!activeReport) return;
    setExporting('md');
    try {
      // Try CrewAI first if configured and connected
      if (crewAIStatus.configured) {
        const crew = await generateCrewAIReport(activeReport);
        if (crew.used && crew.data && crew.data.success) {
          if (crew.data.markdown) {
            const blob = new Blob([crew.data.markdown], { type: 'text/markdown' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `CrewAI_ThreatWeave_${activeReport.id}.md`;
            a.click();
            URL.revokeObjectURL(url);
            addToast('success', 'CrewAI MD Report Downloaded', 'Markdown dossier generated via CrewAI pipeline');
            setExporting(null);
            return;
          }
          if (crew.data.pdf_url || crew.data.result?.download_url) {
            addToast('info', 'CrewAI Report Available', 'CrewAI returned artifact URL; falling back to direct MD export');
          }
        }
      }
      const response = await fetch(`${API_BASE}/api/generate-markdown`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(activeReport),
      });
      if (response.ok) {
        const blob = await response.blob();
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        const cd = response.headers.get('Content-Disposition') || '';
        const match = cd.match(/filename="?([^"]+)"?/);
        a.download = match ? match[1] : `ThreatWeave_${activeReport.id}.md`;
        a.click();
        URL.revokeObjectURL(url);
        addToast('success', 'Report Downloaded', 'Markdown report exported successfully');
      } else {
        const md = buildMarkdown(activeReport);
        const blob = new Blob([md], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `ThreatWeave_${activeReport.id}.md`;
        a.click();
        URL.revokeObjectURL(url);
        addToast('success', 'Report Downloaded', 'Markdown report exported (fallback)');
      }
    } catch (err) {
      const md = buildMarkdown(activeReport);
      const blob = new Blob([md], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `ThreatWeave_${activeReport.id}.md`;
      a.click();
      URL.revokeObjectURL(url);
      addToast('warning', 'Report Downloaded', 'Backend unavailable, used frontend fallback');
    } finally {
      setExporting(null);
    }
  };

  const handleDownloadPDF = async () => {
    if (!activeReport) return;
    setExporting('pdf');
    try {
      // Try CrewAI first if configured
      if (crewAIStatus.configured) {
        const crew = await generateCrewAIReport(activeReport);
        if (crew.used && crew.data && crew.data.success) {
          const pdfUrl = crew.data.pdf_url || crew.data.result?.pdf_url || crew.data.result?.download_url;
          if (pdfUrl) {
            try {
              const fetchRes = await fetch(pdfUrl);
              if (fetchRes.ok) {
                const blob = await fetchRes.blob();
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `CrewAI_ThreatWeave_${activeReport.id}.pdf`;
                a.click();
                URL.revokeObjectURL(url);
                addToast('success', 'CrewAI PDF Downloaded', 'PDF dossier generated via CrewAI pipeline');
                setExporting(null);
                return;
              }
            } catch {
              // fall through
            }
            // If can't download directly, open in new tab
            window.open(pdfUrl, '_blank', 'noopener,noreferrer');
            addToast('success', 'CrewAI PDF Opened', 'CrewAI PDF artifact opened in new tab');
            setExporting(null);
            return;
          }
        }
      }
      const response = await fetch(`${API_BASE}/api/generate-pdf`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(activeReport),
      });
      if (response.ok) {
        const blob = await response.blob();
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        const cd = response.headers.get('Content-Disposition') || '';
        const match = cd.match(/filename="?([^"]+)"?/);
        a.download = match ? match[1] : `ThreatWeave_${activeReport.id}.pdf`;
        a.click();
        URL.revokeObjectURL(url);
        addToast('success', 'PDF Generated', 'Formal PDF dossier exported successfully');
      } else {
        throw new Error('Backend PDF failed');
      }
    } catch (err) {
      try {
        const { jsPDF } = await import('jspdf');
        const autoTable = (await import('jspdf-autotable')).default;
        const doc = new jsPDF();
        const r = activeReport;
        doc.setFontSize(18);
        doc.setTextColor(26, 54, 93);
        doc.setFont('helvetica', 'bold');
        doc.text((r.title || r.threat_title || 'INCIDENT REPORT').substring(0, 55), 105, 20, { align: 'center' });
        doc.setFontSize(9);
        doc.setTextColor(113, 128, 150);
        doc.setFont('helvetica', 'normal');
        doc.text('THREATWEAVE — SIH 2026 Forensic Dossier', 105, 27, { align: 'center' });
        doc.setLineWidth(0.5);
        doc.line(14, 32, 196, 32);
        let y = 40;
        doc.setFontSize(11);
        doc.setTextColor(45, 55, 72);
        doc.setFont('helvetica', 'bold');
        doc.text('REPORT METADATA', 14, y); y += 6;
        const meta = [
          ['Report ID', r.id || 'N/A'],
          ['Incident', r.incident_id || 'N/A'],
          ['Risk', `${r.risk_level || 'N/A'} (${r.risk_score || 'N/A'}/100)`],
          ['Confidence', `${r.confidence || 'N/A'}%`],
          ['Generated', r.generated_at || 'N/A'],
          ['Investigator', r.generated_by || 'ThreatWeave AI'],
        ];
        meta.forEach((m) => {
          doc.setFontSize(8.5);
          doc.setTextColor(113, 128, 150);
          doc.setFont('helvetica', 'bold');
          doc.text(m[0] + ':', 14, y);
          doc.setTextColor(45, 55, 72);
          doc.setFont('helvetica', 'normal');
          doc.text(String(m[1]).substring(0, 80), 55, y);
          y += 5.5;
        });
        y += 4;
        doc.setDrawColor(226, 232, 240);
        doc.line(14, y, 196, y); y += 6;
        doc.setFontSize(12);
        doc.setTextColor(43, 108, 176);
        doc.setFont('helvetica', 'bold');
        doc.text('1. EXECUTIVE SUMMARY', 14, y); y += 7;
        doc.setFontSize(9.5);
        doc.setTextColor(45, 55, 72);
        doc.setFont('helvetica', 'normal');
        const execLines = doc.splitTextToSize(String(r.executive_summary || r.threat_summary || 'N/A'), 180);
        doc.text(execLines, 14, y); y += execLines.length * 5.5 + 5;
        if (y > 260) { doc.addPage(); y = 20; }
        doc.setFontSize(12);
        doc.setTextColor(43, 108, 176);
        doc.setFont('helvetica', 'bold');
        doc.text('2. AFFECTED ASSETS', 14, y); y += 7;
        const assetRows = [
          ['Target User', r.affected_user || 'N/A'],
          ['Target System', r.affected_system || 'N/A'],
          ['Attack Origin', r.source || r.attack_vector || 'N/A'],
          ['Detection', r.detection_time || 'N/A'],
        ];
        autoTable(doc, {
          startY: y,
          head: [['Attribute', 'Value']],
          body: assetRows,
          theme: 'striped',
          styles: { fontSize: 9 },
          headStyles: { fillColor: [43, 108, 176] },
        });
        y = (doc.lastAutoTable || { finalY: y }).finalY + 8;
        if (y > 250) { doc.addPage(); y = 20; }
        doc.setFontSize(12);
        doc.setTextColor(43, 108, 176);
        doc.setFont('helvetica', 'bold');
        doc.text('3. FORENSIC TIMELINE', 14, y); y += 7;
        const tl = r.timeline && r.timeline.length > 0 ? r.timeline : (r.correlated_timeline || []);
        const tlRows = tl.slice(0, 15).map((t, i) => [
          String(i + 1),
          t.timestamp || '',
          (t.event || t.event_type || 'Event').substring(0, 35),
          (t.details || t.action || t.raw_log || '').substring(0, 60),
        ]);
        autoTable(doc, {
          startY: y,
          head: [['#', 'Timestamp', 'Event', 'Details']],
          body: tlRows.length ? tlRows : [['-', '-', 'No events', '-']],
          theme: 'grid',
          styles: { fontSize: 7.5 },
          headStyles: { fillColor: [43, 108, 176] },
        });
        y = (doc.lastAutoTable || { finalY: y }).finalY + 8;
        if (y > 250) { doc.addPage(); y = 20; }
        doc.setFontSize(12);
        doc.setTextColor(43, 108, 176);
        doc.setFont('helvetica', 'bold');
        doc.text('4. ROOT CAUSE', 14, y); y += 7;
        doc.setFontSize(9.5);
        doc.setTextColor(45, 55, 72);
        doc.setFont('helvetica', 'normal');
        const rcLines = doc.splitTextToSize(String(r.root_cause || (r.threat_explanation && (r.threat_explanation.technical || r.threat_explanation.non_technical)) || 'Analysis pending.'), 180);
        doc.text(rcLines, 14, y); y += rcLines.length * 5.5 + 5;
        if (y > 250) { doc.addPage(); y = 20; }
        doc.setFontSize(12);
        doc.setTextColor(214, 158, 46);
        doc.setFont('helvetica', 'bold');
        doc.text('5. CONTAINMENT ACTIONS', 14, y); y += 7;
        doc.setFontSize(9);
        doc.setTextColor(45, 55, 72);
        doc.setFont('helvetica', 'normal');
        const actions = (r.containment_actions && r.containment_actions.length > 0)
          ? r.containment_actions
          : r.recommended_response
            ? r.recommended_response.filter((a) => a.category === 'Containment Actions' || a.category === 'Immediate Actions').map((a) => `[${a.priority}] ${a.action}`)
            : ['None recorded.'];
        actions.forEach((a, i) => { if (y > 275) { doc.addPage(); y = 20; } doc.text(`${i + 1}. ${a}`, 16, y); y += 5; });
        y += 4;
        if (y > 250) { doc.addPage(); y = 20; }
        doc.setFontSize(12);
        doc.setTextColor(56, 161, 105);
        doc.setFont('helvetica', 'bold');
        doc.text('6. REMEDIATION RECOMMENDATIONS', 14, y); y += 7;
        doc.setFontSize(9);
        doc.setTextColor(45, 55, 72);
        doc.setFont('helvetica', 'normal');
        const recs = (r.long_term_recommendations && r.long_term_recommendations.length > 0)
          ? r.long_term_recommendations
          : r.recommended_response
            ? r.recommended_response.filter((a) => a.category === 'Recovery Actions' || a.category === 'Investigation Actions').map((a) => `[${a.priority}] ${a.action}`)
            : ['Pending.'];
        recs.forEach((a, i) => { if (y > 275) { doc.addPage(); y = 20; } doc.text(`${i + 1}. ${a}`, 16, y); y += 5; });
        doc.setFontSize(7.5);
        doc.setTextColor(160, 174, 192);
        doc.text('ThreatWeave SIH 2026 — Page ' + doc.internal.getNumberOfPages(), 14, 292);
        doc.save(`ThreatWeave_${activeReport.id}.pdf`);
        addToast('success', 'PDF Generated', 'Formal PDF dossier exported (jsPDF fallback)');
      } catch (inner) {
        addToast('error', 'PDF Generation Failed', 'Unable to generate PDF. Try Markdown export instead.');
      }
    } finally {
      setExporting(null);
    }
  };

  const handleDownloadJSON = () => {
    if (!activeReport) return;
    const blob = new Blob([JSON.stringify(activeReport, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ThreatWeave_${activeReport.id}.json`;
    a.click();
    URL.revokeObjectURL(url);
    addToast('success', 'Report Downloaded', 'JSON format report exported successfully');
  };

  const handleSaveToMongo = async () => {
    if (!activeReport) return;
    setSaving(true);
    try {
      const res = await fetch(`${API_BASE}/api/reports`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(activeReport),
      });
      const data = await res.json();
      if (data.saved) {
        addToast('success', 'Saved to MongoDB', `Incident report ${activeReport.id} persisted to database successfully`);
      } else {
        addToast('warning', 'Not Saved', data.reason || 'Report stored in memory only');
      }
    } catch (err) {
      addToast('error', 'Save Failed', 'Could not connect to backend API. Report remains in browser session.');
    } finally {
      setSaving(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      {/* Top Header & Report Selector Bar */}
      <div className="p-5 bg-[#1A1C23] border border-white/10 rounded-lg flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-[10px] font-mono uppercase bg-blue-600/10 text-blue-400 border border-blue-500/20 px-2 py-0.5 rounded font-semibold">
              SIH 2026 Formal Dossier
            </span>
            <span className="text-xs text-gray-500 font-mono">Incident Investigation Reports</span>
            <span
              className={`text-[10px] font-mono px-2 py-0.5 rounded border flex items-center gap-1 ${
                dbStatus.loading
                  ? 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20'
                  : dbStatus.connected
                  ? 'bg-green-500/10 text-green-400 border-green-500/20'
                  : 'bg-red-500/10 text-red-400 border-red-500/20'
              }`}
              title={dbStatus.loading ? 'Checking DB connection...' : dbStatus.connected ? 'MongoDB connected' : 'MongoDB offline - using in-memory'}
            >
              {dbStatus.loading ? (
                <Loader2 className="w-3 h-3 animate-spin" />
              ) : dbStatus.connected ? (
                <Database className="w-3 h-3" />
              ) : (
                <AlertCircle className="w-3 h-3" />
              )}
              <span>{dbStatus.loading ? 'DB Connecting' : dbStatus.connected ? 'MongoDB Online' : 'DB Offline'}</span>
            </span>
            <span
              className={`text-[10px] font-mono px-2 py-0.5 rounded border flex items-center gap-1 ${
                !crewAIStatus.checked
                  ? 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20'
                  : crewAIStatus.configured && crewAIStatus.connected
                  ? 'bg-purple-500/10 text-purple-400 border-purple-500/20'
                  : crewAIStatus.configured
                  ? 'bg-orange-500/10 text-orange-400 border-orange-500/20'
                  : 'bg-gray-500/10 text-gray-400 border-gray-500/20'
              }`}
              title={
                !crewAIStatus.checked
                  ? 'Checking CrewAI endpoint...'
                  : crewAIStatus.configured && crewAIStatus.connected
                  ? 'CrewAI Pipeline configured and reachable'
                  : crewAIStatus.configured
                  ? 'CrewAI configured but endpoint unreachable (fallback to local engine)'
                  : 'CrewAI not configured in backend .env'
              }
            >
              {!crewAIStatus.checked ? (
                <Loader2 className="w-3 h-3 animate-spin" />
              ) : crewAIStatus.configured && crewAIStatus.connected ? (
                <Sparkles className="w-3 h-3" />
              ) : (
                <AlertCircle className="w-3 h-3" />
              )}
              <span>
                {!crewAIStatus.checked
                  ? 'CrewAI Probing'
                  : crewAIStatus.configured && crewAIStatus.connected
                  ? 'CrewAI Online'
                  : crewAIStatus.configured
                  ? 'CrewAI Endpoint Unreachable'
                  : 'CrewAI Not Configured'}
              </span>
            </span>
          </div>
          <h2 className="text-base font-bold text-white mt-1">Forensic Incident Reports Generator</h2>
          <p className="text-xs text-gray-400">
            Exportable, audit-grade post-incident documentation generated from agent telemetry
          </p>
        </div>

        {reports.length > 0 && (
          <div className="flex flex-wrap items-center gap-2">
            <select
              value={activeReport?.id}
              onChange={(e) => navigateToReport(e.target.value)}
              className="bg-[#111217] border border-white/10 text-gray-200 text-xs rounded px-3 py-1.5 focus:border-blue-500 focus:outline-none font-mono"
            >
              {reports.map((r) => (
                <option key={r.id} value={r.id}>
                  {r.id}: {(r.title || r.threat_title || '').slice(0, 30)}...
                </option>
              ))}
            </select>

            <button
              onClick={handleCopyMarkdown}
              className="px-3 py-1.5 bg-[#111217] hover:bg-white/5 text-gray-300 text-xs font-semibold rounded border border-white/10 flex items-center gap-1.5 transition-colors cursor-pointer"
              title="Copy as Markdown document"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy MD'}</span>
            </button>

            <button
              onClick={handleDownloadMarkdown}
              disabled={exporting === 'md'}
              className="px-3 py-1.5 bg-[#111217] hover:bg-white/5 text-gray-300 text-xs font-semibold rounded border border-white/10 flex items-center gap-1.5 transition-colors cursor-pointer disabled:opacity-60 disabled:cursor-not-allowed"
              title="Download Markdown file"
            >
              {exporting === 'md' ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <FileCode className="w-3.5 h-3.5 text-purple-400" />}
              <span>{exporting === 'md' ? 'Exporting...' : 'MD'}</span>
            </button>

            <button
              onClick={handleDownloadJSON}
              className="px-3 py-1.5 bg-[#111217] hover:bg-white/5 text-gray-300 text-xs font-semibold rounded border border-white/10 flex items-center gap-1.5 transition-colors cursor-pointer"
              title="Download JSON structure"
            >
              <Download className="w-3.5 h-3.5" />
              <span>JSON</span>
            </button>

            <button
              onClick={handleSaveToMongo}
              disabled={saving || !dbStatus.connected}
              className="px-3 py-1.5 bg-green-600/10 hover:bg-green-600/20 text-green-400 text-xs font-semibold rounded border border-green-500/30 flex items-center gap-1.5 transition-colors cursor-pointer disabled:opacity-60 disabled:cursor-not-allowed"
              title={dbStatus.connected ? 'Persist report to MongoDB' : 'Backend DB unavailable'}
            >
              {saving ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Database className="w-3.5 h-3.5" />}
              <span>{saving ? 'Saving...' : 'Save to DB'}</span>
            </button>

            <button
              onClick={handleDownloadPDF}
              disabled={exporting === 'pdf'}
              className="px-3 py-1.5 bg-[#111217] hover:bg-white/5 text-gray-300 text-xs font-semibold rounded border border-white/10 flex items-center gap-1.5 transition-colors cursor-pointer disabled:opacity-60 disabled:cursor-not-allowed"
              title="Download formal PDF dossier"
            >
              {exporting === 'pdf' ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <FileText className="w-3.5 h-3.5 text-red-400" />}
              <span>{exporting === 'pdf' ? 'Building...' : 'PDF'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold rounded flex items-center gap-1.5 transition-all cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Dossier</span>
            </button>
          </div>
        )}
      </div>

      {reports.length === 0 ? (
        <EmptyState
          title="No Incident Reports Generated"
          description="Generate formal SIH 2026 reports from active incidents to review root cause analyses, timelines, and remediation playbooks. Reports can be exported as PDF/Markdown and persisted to MongoDB."
          actionText="Run SIH-26 Test Scenarios"
          onAction={loadDemoDataset}
        />
      ) : (
        activeReport && (
          <div className="bg-[#1A1C23] border border-white/10 rounded-lg p-8 space-y-8 shadow-2xl max-w-5xl mx-auto print:bg-white print:text-black print:p-0 print:border-none">
            {/* Formal Report Header */}
            <div className="border-b border-white/10 pb-6 space-y-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div>
                  <span className="text-[11px] font-mono text-blue-400 uppercase tracking-widest font-bold">
                    ThreatWeave INCIDENT INVESTIGATION REPORT
                  </span>
                  <h1 className="text-xl font-black text-white mt-1 print:text-black">{activeReport.title}</h1>
                </div>
                <div className="flex items-center gap-2">
                  <RiskBadge level={activeReport.risk_level} size="lg" />
                  <span className={`text-sm font-mono font-bold px-2.5 py-1 rounded border ${
                    (activeReport.risk_level || '').toUpperCase() === 'CRITICAL'
                      ? 'text-red-400 bg-red-500/10 border-red-500/20'
                      : (activeReport.risk_level || '').toUpperCase() === 'HIGH'
                      ? 'text-orange-400 bg-orange-500/10 border-orange-500/20'
                      : (activeReport.risk_level || '').toUpperCase() === 'MEDIUM'
                      ? 'text-yellow-400 bg-yellow-500/10 border-yellow-500/20'
                      : 'text-green-400 bg-green-500/10 border-green-500/20'
                  }`}>
                    Score: {activeReport.risk_score}/100
                  </span>
                </div>
              </div>

              {/* Meta Grid */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 bg-[#111217] rounded-lg border border-white/10 text-xs font-mono print:bg-gray-100 print:text-black">
                <div>
                  <span className="text-gray-500 block text-[10px] uppercase">Report ID</span>
                  <span className="text-white font-semibold print:text-black">{activeReport.id}</span>
                </div>
                <div>
                  <span className="text-gray-500 block text-[10px] uppercase">Incident Ref</span>
                  <span className="text-blue-400 font-semibold">{activeReport.incident_id}</span>
                </div>
                <div>
                  <span className="text-gray-500 block text-[10px] uppercase">Generated At</span>
                  <span className="text-gray-300 print:text-black">{activeReport.generated_at}</span>
                </div>
                <div>
                  <span className="text-gray-500 block text-[10px] uppercase">Investigating Agent</span>
                  <span className="text-gray-300 print:text-black">{activeReport.generated_by}</span>
                </div>
              </div>
            </div>

            {/* 1. Executive Summary */}
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2 print:text-black">
                <span className="w-2 h-2 rounded-full bg-blue-400" />
                1. Executive Summary
              </h3>
              <div className="p-4 bg-[#111217] rounded-lg border border-white/10 text-xs text-gray-300 leading-relaxed font-sans print:bg-white print:text-black">
                {activeReport.executive_summary}
              </div>
            </div>

            {/* 2. Target Entity & Scope */}
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2 print:text-black">
                <span className="w-2 h-2 rounded-full bg-blue-400" />
                2. Target Entity &amp; Attack Vector Scope
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs font-mono">
                <div className="p-3 bg-[#111217] rounded border border-white/10 print:bg-gray-100">
                  <span className="text-gray-500 block text-[10px] uppercase">Target Entity</span>
                  <span className="text-white font-semibold print:text-black">{activeReport.affected_user}</span>
                </div>
                <div className="p-3 bg-[#111217] rounded border border-white/10 print:bg-gray-100">
                  <span className="text-gray-500 block text-[10px] uppercase">Impacted System</span>
                  <span className="text-white font-semibold print:text-black">{activeReport.affected_system}</span>
                </div>
                <div className="p-3 bg-[#111217] rounded border border-white/10 print:bg-gray-100">
                  <span className="text-gray-500 block text-[10px] uppercase">Attack Source</span>
                  <span className="text-red-400 font-semibold">{activeReport.source}</span>
                </div>
              </div>
            </div>

            {/* 3. Attack Timeline Progression - Enhanced Visual */}
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2 print:text-black">
                <span className="w-2 h-2 rounded-full bg-blue-400" />
                3. Chronological Attack Progression Timeline
              </h3>
              <div className="space-y-2 font-mono text-xs relative pl-5 py-2">
                <div className="absolute left-1.5 top-2 bottom-2 w-0.5 bg-gradient-to-b from-red-500/50 via-yellow-500/50 to-green-500/50 rounded-full print:hidden" />
                {(activeReport.timeline && activeReport.timeline.length > 0 ? activeReport.timeline : activeReport.correlated_timeline || []).map((item, idx) => {
                  const sev = ((item.severity || 'info') + '').toUpperCase();
                  const dotColor =
                    sev.includes('CRIT') ? 'bg-red-500' :
                    sev.includes('HIGH') ? 'bg-orange-500' :
                    sev.includes('MED') ? 'bg-yellow-500' :
                    sev.includes('LOW') ? 'bg-green-500' : 'bg-blue-500';
                  return (
                    <div
                      key={idx}
                      className="relative p-3 bg-[#111217] rounded border border-white/10 flex flex-col sm:flex-row sm:items-center justify-between gap-2 print:bg-gray-100 print:text-black"
                    >
                      <span className={`absolute -left-[14px] top-4 w-3 h-3 rounded-full ring-2 ring-[#1A1C23] ${dotColor} print:hidden`} />
                      <div className="flex items-center gap-3">
                        <span className={`w-5 h-5 rounded-full border text-white flex items-center justify-center text-[10px] font-bold shrink-0 ${dotColor}/20 border ${
                          sev.includes('CRIT') ? 'border-red-500/40 text-red-400 bg-red-500/10' :
                          sev.includes('HIGH') ? 'border-orange-500/40 text-orange-400 bg-orange-500/10' :
                          sev.includes('MED') ? 'border-yellow-500/40 text-yellow-400 bg-yellow-500/10' :
                          sev.includes('LOW') ? 'border-green-500/40 text-green-400 bg-green-500/10' :
                          'border-blue-500/40 text-blue-400 bg-blue-500/10'
                        }`}>
                          {idx + 1}
                        </span>
                        <div>
                          <span className="text-white font-semibold print:text-black">{item.event || item.event_type}</span>
                          <div className="text-[11px] text-gray-400 print:text-gray-700">{item.details}</div>
                        </div>
                      </div>
                      <span className="text-gray-500 text-[11px] whitespace-nowrap">{item.timestamp}</span>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* 4. Root Cause Analysis */}
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2 print:text-black">
                <span className="w-2 h-2 rounded-full bg-blue-400" />
                4. Forensic Root Cause Analysis
              </h3>
              <div className="p-4 bg-[#111217] rounded-lg border border-white/10 text-xs text-gray-300 leading-relaxed font-sans print:bg-white print:text-black">
                {activeReport.root_cause}
              </div>
            </div>

            {/* 5. Containment & Remediation Actions */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Containment */}
              <div className="space-y-3">
                <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2 print:text-black">
                  <span className="w-2 h-2 rounded-full bg-yellow-400" />
                  5. Containment Actions Executed
                </h3>
                <div className="p-4 bg-[#111217] rounded-lg border border-white/10 space-y-2 text-xs print:bg-gray-100 print:text-black">
                  <ul className="space-y-2 font-sans text-gray-300 print:text-black">
                    {(activeReport.containment_actions || []).map((act, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <span className="text-yellow-400 font-bold">&bull;</span>
                        <span>{act}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Long-term Remediation */}
              <div className="space-y-3">
                <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2 print:text-black">
                  <span className="w-2 h-2 rounded-full bg-green-400" />
                  6. Strategic Hardening Recommendations
                </h3>
                <div className="p-4 bg-[#111217] rounded-lg border border-white/10 space-y-2 text-xs print:bg-gray-100 print:text-black">
                  <ul className="space-y-2 font-sans text-gray-300 print:text-black">
                    {(activeReport.long_term_recommendations || []).map((rec, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <span className="text-green-400 font-bold">&bull;</span>
                        <span>{rec}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>

            {/* Footer Sign-off */}
            <div className="pt-6 border-t border-white/10 flex flex-col sm:flex-row sm:items-center justify-between text-[11px] font-mono text-gray-500 gap-2">
              <span>ThreatWeave Security Operations Platform</span>
              <span>SIH 2026 Problem PS-01 Verified Submission</span>
            </div>
          </div>
        )
      )}
    </div>
  );
};
