import React, { useState } from 'react';
import { useSOC } from '../context/SOCContext';
import {
  FileCheck2,
  Download,
  Printer,
  Copy,
  Check,
  ShieldAlert,
  Clock,
  Layers,
  ChevronRight,
  User,
  ExternalLink,
} from 'lucide-react';
import { RiskBadge } from '../components/common/RiskBadge';
import { StatusBadge } from '../components/common/StatusBadge';
import { EmptyState } from '../components/common/EmptyState';

export const ReportsPage = () => {
  const {
    reports,
    selectedReportId,
    navigateToReport,
    incidents,
    generateReportForIncident,
    addToast,
    loadDemoDataset,
  } = useSOC();

  const [copied, setCopied] = useState(false);

  const activeReport =
    reports.find((r) => r.id === selectedReportId) || reports[0];

  const handleCopyMarkdown = () => {
    if (!activeReport) return;
    const markdown = `# ${activeReport.title}
**Report ID:** ${activeReport.id}
**Incident ID:** ${activeReport.incident_id}
**Generated Date:** ${activeReport.generated_at}
**Generated By:** ${activeReport.generated_by}
**Risk Level:** ${activeReport.risk_level} (Score: ${activeReport.risk_score}/100)

## Executive Summary
${activeReport.executive_summary}

## Incident Context
- **Target Entity:** ${activeReport.affected_user}
- **Target Host:** ${activeReport.affected_system}
- **Attack Origin:** ${activeReport.source}

## Attack Progression & Forensic Timeline
${activeReport.timeline.map((t) => `- **[${t.timestamp}]** ${t.event} (${t.details})`).join('\n')}

## Root Cause Analysis
${activeReport.root_cause}

## Immediate Containment Actions Taken
${activeReport.containment_actions.map((c) => `- ${c}`).join('\n')}

## Long-term Remediation Recommendations
${activeReport.long_term_recommendations.map((r) => `- ${r}`).join('\n')}

---
*SIH 2026 Problem PS-01 UrbanSOC Autonomous Cyber Dossier*
`;
    navigator.clipboard.writeText(markdown);
    setCopied(true);
    addToast('Report Copied', 'Markdown formatted report copied to clipboard', 'success');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJSON = () => {
    if (!activeReport) return;
    const blob = new Blob([JSON.stringify(activeReport, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `UrbanSOC_${activeReport.id}.json`;
    a.click();
    URL.revokeObjectURL(url);
    addToast('Report Downloaded', 'JSON format report exported successfully', 'success');
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      {/* Top Header & Report Selector Bar */}
      <div className="p-5 bg-[#1A1C23] border border-white/10 rounded-lg flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-[10px] font-mono uppercase bg-blue-600/10 text-blue-400 border border-blue-500/20 px-2 py-0.5 rounded font-semibold">
              SIH 2026 Formal Dossier
            </span>
            <span className="text-xs text-gray-500 font-mono">Incident Investigation Reports</span>
          </div>
          <h2 className="text-base font-bold text-white mt-1">Forensic Incident Reports Generator</h2>
          <p className="text-xs text-gray-400">
            Exportable, audit-grade post-incident documentation generated from agent telemetry
          </p>
        </div>

        {reports.length > 0 && (
          <div className="flex flex-wrap items-center gap-2">
            {/* Report Selector */}
            <select
              value={activeReport?.id}
              onChange={(e) => navigateToReport(e.target.value)}
              className="bg-[#111217] border border-white/10 text-gray-200 text-xs rounded px-3 py-1.5 focus:border-blue-500 focus:outline-none font-mono"
            >
              {reports.map((r) => (
                <option key={r.id} value={r.id}>
                  {r.id}: {r.title.slice(0, 30)}...
                </option>
              ))}
            </select>

            {/* Export Buttons */}
            <button
              onClick={handleCopyMarkdown}
              className="px-3 py-1.5 bg-[#111217] hover:bg-white/5 text-gray-300 text-xs font-semibold rounded border border-white/10 flex items-center gap-1.5 transition-colors cursor-pointer"
              title="Copy as Markdown document"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy MD'}</span>
            </button>

            <button
              onClick={handleDownloadJSON}
              className="px-3 py-1.5 bg-[#111217] hover:bg-white/5 text-gray-300 text-xs font-semibold rounded border border-white/10 flex items-center gap-1.5 transition-colors cursor-pointer"
              title="Download JSON structure"
            >
              <Download className="w-3.5 h-3.5" />
              <span>JSON</span>
            </button>

            <button
              onClick={handlePrint}
              className="px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold rounded flex items-center gap-1.5 transition-all cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Dossier</span>
            </button>
          </div>
        )}
      </div>

      {reports.length === 0 ? (
        <EmptyState
          title="No Incident Reports Generated"
          description="Generate formal SIH 2026 reports from active incidents to review root cause analyses, timelines, and remediation playbooks."
          actionText="Run SIH-26 Test Scenarios"
          onAction={loadDemoDataset}
        />
      ) : (
        activeReport && (
          <div className="bg-[#1A1C23] border border-white/10 rounded-lg p-8 space-y-8 shadow-2xl max-w-5xl mx-auto print:bg-white print:text-black print:p-0 print:border-none">
            {/* Formal Report Header */}
            <div className="border-b border-white/10 pb-6 space-y-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div>
                  <span className="text-[11px] font-mono text-blue-400 uppercase tracking-widest font-bold">
                    URBANSOC INCIDENT INVESTIGATION REPORT
                  </span>
                  <h1 className="text-xl font-black text-white mt-1 print:text-black">{activeReport.title}</h1>
                </div>
                <div className="flex items-center gap-2">
                  <RiskBadge level={activeReport.risk_level} size="lg" />
                  <span className="text-sm font-mono font-bold text-red-400 bg-red-500/10 px-2.5 py-1 rounded border border-red-500/20">
                    Score: {activeReport.risk_score}/100
                  </span>
                </div>
              </div>

              {/* Meta Grid */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 bg-[#111217] rounded-lg border border-white/10 text-xs font-mono print:bg-gray-100 print:text-black">
                <div>
                  <span className="text-gray-500 block text-[10px] uppercase">Report ID</span>
                  <span className="text-white font-semibold print:text-black">{activeReport.id}</span>
                </div>
                <div>
                  <span className="text-gray-500 block text-[10px] uppercase">Incident Ref</span>
                  <span className="text-blue-400 font-semibold">{activeReport.incident_id}</span>
                </div>
                <div>
                  <span className="text-gray-500 block text-[10px] uppercase">Generated At</span>
                  <span className="text-gray-300 print:text-black">{activeReport.generated_at}</span>
                </div>
                <div>
                  <span className="text-gray-500 block text-[10px] uppercase">Investigating Agent</span>
                  <span className="text-gray-300 print:text-black">{activeReport.generated_by}</span>
                </div>
              </div>
            </div>

            {/* 1. Executive Summary */}
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2 print:text-black">
                <span className="w-2 h-2 rounded-full bg-blue-400" />
                1. Executive Summary
              </h3>
              <div className="p-4 bg-[#111217] rounded-lg border border-white/10 text-xs text-gray-300 leading-relaxed font-sans print:bg-white print:text-black">
                {activeReport.executive_summary}
              </div>
            </div>

            {/* 2. Target Entity & Scope */}
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2 print:text-black">
                <span className="w-2 h-2 rounded-full bg-blue-400" />
                2. Target Entity &amp; Attack Vector Scope
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs font-mono">
                <div className="p-3 bg-[#111217] rounded border border-white/10 print:bg-gray-100">
                  <span className="text-gray-500 block text-[10px] uppercase">Target Entity</span>
                  <span className="text-white font-semibold print:text-black">{activeReport.affected_user}</span>
                </div>
                <div className="p-3 bg-[#111217] rounded border border-white/10 print:bg-gray-100">
                  <span className="text-gray-500 block text-[10px] uppercase">Impacted System</span>
                  <span className="text-white font-semibold print:text-black">{activeReport.affected_system}</span>
                </div>
                <div className="p-3 bg-[#111217] rounded border border-white/10 print:bg-gray-100">
                  <span className="text-gray-500 block text-[10px] uppercase">Attack Source</span>
                  <span className="text-red-400 font-semibold">{activeReport.source}</span>
                </div>
              </div>
            </div>

            {/* 3. Attack Timeline Progression */}
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2 print:text-black">
                <span className="w-2 h-2 rounded-full bg-blue-400" />
                3. Chronological Attack Progression Timeline
              </h3>
              <div className="space-y-2 font-mono text-xs">
                {activeReport.timeline.map((item, idx) => (
                  <div
                    key={idx}
                    className="p-3 bg-[#111217] rounded border border-white/10 flex flex-col sm:flex-row sm:items-center justify-between gap-2 print:bg-gray-100 print:text-black"
                  >
                    <div className="flex items-center gap-3">
                      <span className="w-5 h-5 rounded-full bg-blue-600/10 border border-blue-500/20 text-blue-400 flex items-center justify-center text-[10px] font-bold">
                        {idx + 1}
                      </span>
                      <div>
                        <span className="text-white font-semibold print:text-black">{item.event}</span>
                        <div className="text-[11px] text-gray-400 print:text-gray-700">{item.details}</div>
                      </div>
                    </div>
                    <span className="text-gray-500 text-[11px] whitespace-nowrap">{item.timestamp}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* 4. Root Cause Analysis */}
            <div className="space-y-3">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2 print:text-black">
                <span className="w-2 h-2 rounded-full bg-blue-400" />
                4. Forensic Root Cause Analysis
              </h3>
              <div className="p-4 bg-[#111217] rounded-lg border border-white/10 text-xs text-gray-300 leading-relaxed font-sans print:bg-white print:text-black">
                {activeReport.root_cause}
              </div>
            </div>

            {/* 5. Containment & Remediation Actions */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Containment */}
              <div className="space-y-3">
                <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2 print:text-black">
                  <span className="w-2 h-2 rounded-full bg-yellow-400" />
                  5. Containment Actions Executed
                </h3>
                <div className="p-4 bg-[#111217] rounded-lg border border-white/10 space-y-2 text-xs print:bg-gray-100 print:text-black">
                  <ul className="space-y-2 font-sans text-gray-300 print:text-black">
                    {activeReport.containment_actions.map((act, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <span className="text-yellow-400 font-bold">&bull;</span>
                        <span>{act}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Long-term Remediation */}
              <div className="space-y-3">
                <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono flex items-center gap-2 print:text-black">
                  <span className="w-2 h-2 rounded-full bg-green-400" />
                  6. Strategic Hardening Recommendations
                </h3>
                <div className="p-4 bg-[#111217] rounded-lg border border-white/10 space-y-2 text-xs print:bg-gray-100 print:text-black">
                  <ul className="space-y-2 font-sans text-gray-300 print:text-black">
                    {activeReport.long_term_recommendations.map((rec, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <span className="text-green-400 font-bold">&bull;</span>
                        <span>{rec}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>

            {/* Footer Sign-off */}
            <div className="pt-6 border-t border-white/10 flex flex-col sm:flex-row sm:items-center justify-between text-[11px] font-mono text-gray-500 gap-2">
              <span>UrbanSOC Autonomous Multi-Agent Cybersecurity Platform</span>
              <span>SIH 2026 Problem PS-01 Verified Submission</span>
            </div>
          </div>
        )
      )}
    </div>
  );
};
